[gravity]
domain = "gravity"
host = "0.0.0.0:4222"

[subscriber]
subscriberID = "mongodb_transmitter"
subscriberName = "MongoDB Transmitter"
stateStore = "./statestore"
workerCount = 4
chunkSize = 2048
verbose = true
pipelineStart = 0
pipelineEnd = -1

# Authentication
appID = "anonymous"
accessKey = ""

[initialLoad]
enabled = true
omittedCount = 100000

[bufferInput]
chunkSize = 5000
timeout = 50
#unit: millisecond

[rules]
subscription = "./settings/subscriptions.json"


[mongodb]
dbname = "gravity"
uri = "mongodb://0.0.0.0:27017"
#uri = "mongodb://test:test@mongo-cluster.cluster-12345.us-east-2.docdb.amazonaws.com:27017/?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&connectTimeoutMS=10000&connect=direct"
#ca_file = "./test.pem"
