[service]
port = 44143

[mongodb]
dbname = "gravity"
uri = "mongodb://0.0.0.0:27017"
#uri = "mongodb://test:test@mongo-cluster.cluster-12345.us-east-2.docdb.amazonaws.com:27017/?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&connectTimeoutMS=10000&connect=direct"
#ca_file = "./test.pem"
