[gravity]
domain = "gravity"
host = "0.0.0.0:4222"

[subscriber]
subscriber_id = "mongodb_transmitter"
subscriber_name = "MongoDB Transmitter"
state_store = "./statestore"
worker_count = 4
verbose = true
pipeline_start = 0
pipeline_end = -1


[initial_load]
enabled = true
omitted_count = 100000


[rules]
subscription = "./settings/subscriptions.json"


[mongodb]
dbname = "gravity"
uri = "mongodb://0.0.0.0:27017"
#uri = "mongodb://test:test@mongo-cluster.cluster-12345.us-east-2.docdb.amazonaws.com:27017/?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&connectTimeoutMS=10000&connect=direct"
#ca_file = "./test.pem"
